// The constructions the paper calls "forced, not fitted" -- pinned.
//
// A review observed that test coverage was thinnest exactly on the claims the
// paper leans hardest on, and it was right: `alphaStep` appeared nowhere in
// tests/, so the headline stabilization result rested on a hand-run benchmark;
// the three stated properties of the covariant averaging rule were untested or
// tested vacuously; and the series-conductance weight was pinned only in its
// uniform case. This file covers those.
//
// The pattern this session kept hitting is the reason to bother: a silent
// degradation (a hierarchy that collapsed to one level, a transfer switch that
// reached nothing, a weight rule that differed only by a constant the line
// search absorbs) produces numbers that look plausible and are meaningless.
// Each check below is written to fail loudly in exactly that situation.
#include <cmath>
#include <complex>
#include <random>
#include <vector>

#include "doctest.h"
#include "solvers/GaugeMultigrid.h"

using namespace bochner;
using cd = std::complex<double>;

namespace {

// Open (non-periodic) lattice with trivial links: the connection is absent, so
// the covariant transfer must reduce to ordinary geometric interpolation.
GaugeLattice trivialLattice(int n) {
  GaugeLattice L;
  L.lx = L.ly = L.lz = n;
  L.periodic = false;
  L.w = 1.0;
  L.lkx.assign(static_cast<std::size_t>(L.numLinksX()), 0.0);
  L.lky.assign(static_cast<std::size_t>(L.numLinksY()), 0.0);
  L.lkz.assign(static_cast<std::size_t>(L.numLinksZ()), 0.0);
  L.buildTransports();
  return L;
}

// A PURE GAUGE: links generated by a site-dependent phase, U_ij = g_j / g_i,
// which is what the forward angle lkx = alpha(i+1) - alpha(i) encodes. Zero
// curvature by construction, so the bundle is trivial and the covariantly
// constant section exists globally -- it is psi_i = g_i = e^{i alpha_i}.
GaugeLattice pureGaugeLattice(int n, std::vector<double>* alphaOut) {
  GaugeLattice L;
  L.lx = L.ly = L.lz = n;
  L.periodic = false;
  L.w = 1.0;
  std::vector<double> alpha(static_cast<std::size_t>(n) * n * n);
  std::mt19937_64 rng(20260721);
  std::uniform_real_distribution<double> U(-M_PI, M_PI);
  for (auto& a : alpha) a = U(rng);
  L.lkx.assign(static_cast<std::size_t>(L.numLinksX()), 0.0);
  L.lky.assign(static_cast<std::size_t>(L.numLinksY()), 0.0);
  L.lkz.assign(static_cast<std::size_t>(L.numLinksZ()), 0.0);
  const auto at = [&](int i, int j, int k) {
    return alpha[static_cast<std::size_t>((i * n + j) * n + k)];
  };
  for (int i = 0; i < n; ++i)
    for (int j = 0; j < n; ++j)
      for (int k = 0; k < n; ++k) {
        if (i + 1 < n) L.lkx[static_cast<std::size_t>((i * n + j) * n + k)] = at(i + 1, j, k) - at(i, j, k);
        if (j + 1 < n) L.lky[static_cast<std::size_t>((i * (n - 1) + j) * n + k)] = at(i, j + 1, k) - at(i, j, k);
        if (k + 1 < n) L.lkz[static_cast<std::size_t>((i * n + j) * (n - 1) + k)] = at(i, j, k + 1) - at(i, j, k);
      }
  L.buildTransports();
  if (alphaOut) *alphaOut = alpha;
  return L;
}

GaugeLattice fluxTorus(int n, int nPhi) {
  const double phi = 2.0 * M_PI * nPhi / (double(n) * n);
  const std::size_t N = static_cast<std::size_t>(n) * n * n;
  std::vector<double> lkx(N, 0.0), lky(N, 0.0), lkz(N, 0.0);
  const auto idx = [&](int i, int j, int k) { return (i * n + j) * n + k; };
  for (int i = 0; i < n; ++i)
    for (int j = 0; j < n; ++j)
      for (int k = 0; k < n; ++k) {
        lkx[idx(i, j, k)] = -phi * j;
        if (j == n - 1) lky[idx(i, j, k)] = 2.0 * M_PI * nPhi * i / double(n);
      }
  return gaugeLatticePeriodic(n, n, n, double(n) * n, lkx, lky, lkz);
}

std::vector<cd> structuredRhs(std::size_t n) {
  std::vector<cd> b(n);
  for (std::size_t i = 0; i < n; ++i) b[i] = cd(std::sin(0.7 * i), std::cos(0.3 * i));
  return b;
}

double energyNorm(const GaugeLattice& L, const std::vector<cd>& v) {
  const std::vector<cd> Lv = applyConnectionLaplacian(L, v);
  cd s(0, 0);
  for (std::size_t i = 0; i < v.size(); ++i) s += std::conj(v[i]) * Lv[i];
  return std::sqrt(std::max(0.0, s.real()));
}

}  // namespace

// --- the averaging rule, eq:covariant-average ------------------------------

TEST_CASE("trivial connection: the covariant transfer IS multilinear interpolation") {
  const int n = 8;
  const GaugeLattice L = trivialLattice(n);
  const auto levels = buildGaugeLevels(L);
  REQUIRE(levels.size() >= 2);
  const GaugeLattice& C = levels[1];

  // A coarse field that is affine in the coordinates. Ordinary multilinear
  // interpolation reproduces an affine function exactly, so if the covariant
  // fill really degenerates to multilinear interpolation at U = 1, the
  // prolonged field must be the same affine function on the fine grid --
  // where fine node (2I,2J,2K) sits at coarse (I,J,K), i.e. fine coordinate
  // x maps to coarse x/2.
  std::vector<cd> c(static_cast<std::size_t>(C.numNodes()));
  const auto aff = [](double x, double y, double z) { return cd(1.0 + 2 * x - 3 * y + 0.5 * z, 0.0); };
  for (int I = 0; I < C.lx; ++I)
    for (int J = 0; J < C.ly; ++J)
      for (int K = 0; K < C.lz; ++K)
        c[static_cast<std::size_t>(C.index(I, J, K))] = aff(I, J, K);

  const std::vector<cd> f = prolongGauge(L, c);

  // Interior only: the boundary fill has one-sided stencils, where an affine
  // function is still reproduced along the filled axes but the claim is about
  // the interpolation rule, not the boundary closure.
  for (int i = 1; i + 1 < L.lx; ++i)
    for (int j = 1; j + 1 < L.ly; ++j)
      for (int k = 1; k + 1 < L.lz; ++k) {
        const cd want = aff(0.5 * i, 0.5 * j, 0.5 * k);
        const cd got = f[static_cast<std::size_t>(L.index(i, j, k))];
        CHECK(got.real() == doctest::Approx(want.real()).epsilon(1e-12));
        CHECK(std::abs(got.imag()) < 1e-12);
      }
}

TEST_CASE("pure gauge: the covariantly constant section prolongs to ITSELF") {
  // The paper: "for a pure gauge it transports exactly". The previous test of
  // this only asserted |psi| > 0.1, which tolerates a 90% magnitude loss where
  // the claim is |psi| == 1 everywhere. Here the whole section is pinned, phase
  // included, to round-off.
  const int n = 8;
  std::vector<double> alpha;
  const GaugeLattice L = pureGaugeLattice(n, &alpha);
  const auto levels = buildGaugeLevels(L);
  REQUIRE(levels.size() >= 2);
  const GaugeLattice& C = levels[1];

  // psi_i = e^{i alpha_i} is covariantly constant: psi_j = U_ij psi_i exactly.
  std::vector<cd> c(static_cast<std::size_t>(C.numNodes()));
  for (int I = 0; I < C.lx; ++I)
    for (int J = 0; J < C.ly; ++J)
      for (int K = 0; K < C.lz; ++K)
        c[static_cast<std::size_t>(C.index(I, J, K))] =
            std::polar(1.0, alpha[static_cast<std::size_t>((2 * I * n + 2 * J) * n + 2 * K)]);

  const std::vector<cd> f = prolongGauge(L, c);

  double worstMag = 1e9, worstErr = 0.0;
  for (int i = 0; i < L.lx; ++i)
    for (int j = 0; j < L.ly; ++j)
      for (int k = 0; k < L.lz; ++k) {
        const cd got = f[static_cast<std::size_t>(L.index(i, j, k))];
        const cd want = std::polar(1.0, alpha[static_cast<std::size_t>((i * n + j) * n + k)]);
        worstMag = std::min(worstMag, std::abs(got));
        worstErr = std::max(worstErr, std::abs(got - want));
      }
  // The real claim, not a floor: unit modulus and the exact section.
  CHECK(worstMag == doctest::Approx(1.0).epsilon(1e-12));
  CHECK(worstErr < 1e-12);
}

TEST_CASE("the fill satisfies the covariant mean-value property it is derived from") {
  // "the interpolation weights are forced by harmonicity, not fitted": each
  // pass fills a node with the weighted covariant mean of its already-filled
  // neighbours, eq:covariant-average. Pass 1 fills nodes with exactly one odd
  // coordinate from their two even neighbours along that axis, so those nodes
  // are checkable in closed form against the formula.
  const int n = 8, nPhi = 2;
  const GaugeLattice L = fluxTorus(n, nPhi);
  const auto levels = buildGaugeLevels(L);
  REQUIRE(levels.size() >= 2);
  const GaugeLattice& C = levels[1];

  std::vector<cd> c = structuredRhs(static_cast<std::size_t>(C.numNodes()));
  const std::vector<cd> f = prolongGauge(L, c);

  // Node (i,j,k) with i odd, j and k even: neighbours (i-1,*) and (i+1,*), both
  // even and hence copied straight from the coarse vector. The forward link
  // lkx[i-1] transports (i-1) -> i, and lkx[i] transports i -> (i+1), so the
  // value at i is the mean of e^{+i lk[i-1]} psi_{i-1} and e^{-i lk[i]} psi_{i+1}.
  int checked = 0;
  for (int i = 1; i < L.lx; i += 2)
    for (int j = 0; j < L.ly; j += 2)
      for (int k = 0; k < L.lz; k += 2) {
        const int lo = (i - 1 + L.lx) % L.lx, hi = (i + 1) % L.lx;
        const cd psiLo = c[static_cast<std::size_t>(C.index(lo / 2, j / 2, k / 2))];
        const cd psiHi = c[static_cast<std::size_t>(C.index(hi / 2, j / 2, k / 2))];
        const cd tLo = std::polar(1.0, L.lkx[static_cast<std::size_t>((lo * L.ly + j) * L.lz + k)]);
        const cd tHi = std::polar(1.0, L.lkx[static_cast<std::size_t>((i * L.ly + j) * L.lz + k)]);
        const cd want = 0.5 * (tLo * psiLo + std::conj(tHi) * psiHi);
        const cd got = f[static_cast<std::size_t>(L.index(i, j, k))];
        CHECK(std::abs(got - want) < 1e-12);
        ++checked;
      }
  REQUIRE(checked > 0);
}

// --- the line search, the paper's headline stabilization -------------------

TEST_CASE("alpha step is what separates convergence from divergence") {
  // tab:ablation's central row, as a test rather than a hand-run binary:
  // on the coherently frustrated flux torus the stabilized cycle converges and
  // raw injection (alpha == 1) diverges. If this ever silently passes with
  // alphaStep=false, the paper's headline ingredient has stopped being
  // load-bearing and the claim needs revisiting.
  const int n = 8, nPhi = 4;
  const GaugeLattice L = fluxTorus(n, nPhi);
  const auto levels = buildGaugeLevels(L);
  const std::vector<cd> b = structuredRhs(static_cast<std::size_t>(L.numNodes()));

  MgOptions on;
  on.tol = 1e-8;
  on.maxCycles = 60;
  std::vector<cd> x(b.size(), cd(0, 0));
  const MgResult withAlpha = vcycleSolve(levels, b, x, on);
  CHECK(withAlpha.relResidual < 1e-8);
  CHECK(withAlpha.cycles < 30);

  MgOptions off = on;
  off.alphaStep = false;
  off.maxCycles = 30;
  std::vector<cd> y(b.size(), cd(0, 0));
  const MgResult noAlpha = vcycleSolve(levels, b, y, off);
  CHECK(noAlpha.relResidual > 1.0);  // diverged, not merely slow
}

TEST_CASE("the stabilized cycle is monotone in the energy norm") {
  // prop:descent: the alpha-scaled coarse correction cannot increase the
  // A-energy of the error, and the smoother is an energy contraction, so the
  // error's energy norm must decrease every cycle. This is the property that
  // makes the non-Galerkin cycle safe, so a regression here is a correctness
  // regression, not a performance one.
  const int n = 8, nPhi = 4;
  const GaugeLattice L = fluxTorus(n, nPhi);
  const auto levels = buildGaugeLevels(L);

  // Exact solution known by construction: pick xStar, set b = L xStar.
  const std::vector<cd> xStar = structuredRhs(static_cast<std::size_t>(L.numNodes()));
  const std::vector<cd> b = applyConnectionLaplacian(L, xStar);

  MgOptions o;
  o.tol = 0.0;  // never stop early; we want the per-cycle history
  o.maxCycles = 1;
  std::vector<cd> x(b.size(), cd(0, 0));
  double prev = 1e300;
  for (int cycle = 0; cycle < 8; ++cycle) {
    vcycleSolve(levels, b, x, o);
    std::vector<cd> e(x.size());
    for (std::size_t i = 0; i < x.size(); ++i) e[i] = x[i] - xStar[i];
    const double en = energyNorm(L, e);
    CHECK(en < prev);
    prev = en;
  }
}

// --- the series-conductance coarse weight ---------------------------------

TEST_CASE("series-conductance rule, in its NON-uniform case") {
  // Only the uniform w -> w/4 case was pinned. The rule is
  // W = w_a w_b / (2 (w_a + w_b)), which reduces to w/4 when w_a = w_b -- so a
  // test that only ever sees equal weights cannot tell the series rule from
  // any other rule agreeing there (the arithmetic mean (w_a+w_b)/8 among them).
  const int n = 8;
  GaugeLattice L = trivialLattice(n);

  // Alternating weights along x so adjacent pairs genuinely differ.
  std::vector<double> wx(static_cast<std::size_t>(L.numLinksX())),
      wy(static_cast<std::size_t>(L.numLinksY()), 1.0),
      wz(static_cast<std::size_t>(L.numLinksZ()), 1.0);
  for (int i = 0; i + 1 < L.lx; ++i)
    for (int j = 0; j < L.ly; ++j)
      for (int k = 0; k < L.lz; ++k)
        wx[static_cast<std::size_t>((i * L.ly + j) * L.lz + k)] = (i % 2 == 0) ? 1.0 : 5.0;
  L.setEdgeWeights(wx, wy, wz);

  const auto levels = buildGaugeLevels(L);
  REQUIRE(levels.size() >= 2);
  const GaugeLattice& C = levels[1];
  REQUIRE(C.weighted());

  // Coarse x-edge I spans fine edges 2I (w=1) and 2I+1 (w=5):
  //   series      = 1*5 / (2*(1+5))       = 0.41666...
  //   arithmetic  = (1+5)/4 = 1.5, or /8  = 0.75      -- both clearly distinct
  const double want = 1.0 * 5.0 / (2.0 * (1.0 + 5.0));
  for (int I = 0; I + 1 < C.lx; ++I)
    for (int J = 0; J < C.ly; ++J)
      for (int K = 0; K < C.lz; ++K)
        CHECK(C.wx[static_cast<std::size_t>((I * C.ly + J) * C.lz + K)] ==
              doctest::Approx(want).epsilon(1e-12));

  // And the uniform case still collapses to w/4, so the weighted hierarchy
  // contains the unweighted one.
  CHECK(C.wy[0] == doctest::Approx(0.25).epsilon(1e-12));
}
